-- DLSN Imports V11 — Supabase setup
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(user_id,display_name,email)
  values(new.id,coalesce(new.raw_user_meta_data->>'name','Cliente DLSN'),new.email)
  on conflict(user_id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where user_id=auth.uid() and role='admin');
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  brand text not null,
  model text,
  color text,
  kind text not null default 'Tênis',
  old_price numeric(12,2),
  price numeric(12,2) not null default 0,
  image text,
  sizes int[] not null default array[38,39,40,41,42,43,44],
  stock int not null default 1997,
  active boolean not null default true,
  featured boolean not null default false,
  best_seller boolean not null default false,
  promotion boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists color text;
alter table public.products add column if not exists old_price numeric(12,2);
alter table public.products add column if not exists featured boolean not null default false;
alter table public.products add column if not exists best_seller boolean not null default false;
alter table public.products add column if not exists promotion boolean not null default false;
alter table public.products add column if not exists active boolean not null default true;
alter table public.products add column if not exists sizes int[] not null default array[38,39,40,41,42,43,44];
alter table public.products add column if not exists stock int not null default 1997;

create table if not exists public.site_settings (
  id int primary key default 1,
  announcement text,
  hero_banner text,
  instagram text,
  whatsapp text,
  store_description text,
  footer_note text,
  bg_color text,
  card_color text,
  text_color text,
  radius int,
  font_family text,
  logo_spin_seconds int,
  visible_brands text,
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_slug text not null,
  reviewer_name text,
  rating int not null check(rating between 1 and 5),
  text text not null check(char_length(text)<=1200),
  status text not null default 'pending' check(status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  unique(user_id,product_slug)
);

alter table public.reviews add column if not exists reviewer_name text;
alter table public.site_settings add column if not exists visible_brands text;

create table if not exists public.review_images (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references public.reviews(id) on delete cascade,
  url text not null,
  path text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.site_settings enable row level security;
alter table public.reviews enable row level security;
alter table public.review_images enable row level security;

drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read" on public.profiles for select using(auth.uid()=user_id or public.is_admin());
drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products for select using(active=true or public.is_admin());
drop policy if exists "products admin all" on public.products;
create policy "products admin all" on public.products for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "settings public read" on public.site_settings;
create policy "settings public read" on public.site_settings for select using(true);
drop policy if exists "settings admin write" on public.site_settings;
create policy "settings admin write" on public.site_settings for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "reviews public approved" on public.reviews;
create policy "reviews public approved" on public.reviews for select using(status='approved' or auth.uid()=user_id or public.is_admin());
drop policy if exists "reviews customer insert" on public.reviews;
create policy "reviews customer insert" on public.reviews for insert with check(auth.uid()=user_id and status='pending');
drop policy if exists "reviews admin update" on public.reviews;
create policy "reviews admin update" on public.reviews for update using(public.is_admin());
drop policy if exists "reviews admin delete" on public.reviews;
create policy "reviews admin delete" on public.reviews for delete using(public.is_admin());
drop policy if exists "review images read" on public.review_images;
create policy "review images read" on public.review_images for select using(true);
drop policy if exists "review images insert" on public.review_images;
create policy "review images insert" on public.review_images for insert with check(exists(select 1 from public.reviews r where r.id=review_id and r.user_id=auth.uid()));

insert into public.site_settings(id,announcement,hero_banner,instagram,whatsapp,store_description,footer_note,bg_color,card_color,text_color,radius,font_family,logo_spin_seconds)
values(1,'DLSN IMPORTS • SNEAKERS PREMIUM • TRÊS LAGOAS - MS','assets/images/theme/dlsn-boas-vindas-v2.jpg','@dlsn_imports','5567996773494','Sneakers selecionados com atendimento digital em Três Lagoas — MS.','Três Lagoas — MS','#0a0b0e','#15171b','#ffffff',16,'Inter',8)
on conflict(id) do nothing;

insert into storage.buckets(id,name,public) values('review-images','review-images',true) on conflict(id) do nothing;

drop policy if exists "review storage upload" on storage.objects;
create policy "review storage upload" on storage.objects for insert to authenticated with check(bucket_id='review-images' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "review storage public read" on storage.objects;
create policy "review storage public read" on storage.objects for select using(bucket_id='review-images');

-- Substitui o estoque antigo pelo catálogo V12
DELETE FROM public.products;

insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike NOCTA Glide — Black','nike-nocta-glide-black','Nike','NOCTA Glide','Black',439.99,399.99,'assets/images/products/stock/nike-nocta-glide-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike NOCTA Glide — Black Red','nike-nocta-glide-black-red','Nike','NOCTA Glide','Black Red',439.99,399.99,'assets/images/products/stock/nike-nocta-glide-black-red.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike NOCTA Glide — Black White','nike-nocta-glide-black-white','Nike','NOCTA Glide','Black White',439.99,399.99,'assets/images/products/stock/nike-nocta-glide-black-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('ASICS GEL-NYC — Strawberries Cream','asics-gel-nyc-strawberries-cream','ASICS','GEL-NYC','Strawberries Cream',449.99,419.99,'assets/images/products/stock/asics-gel-nyc-strawberries-cream.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('ASICS GEL-NYC — Cream Oyster','asics-gel-nyc-cream-oyster','ASICS','GEL-NYC','Cream Oyster',449.99,419.99,'assets/images/products/stock/asics-gel-nyc-cream-oyster.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('ASICS GEL-NYC — Mid Ivory','asics-gel-nyc-mid-ivory','ASICS','GEL-NYC','Mid Ivory',449.99,419.99,'assets/images/products/stock/asics-gel-nyc-mid-ivory.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('ASICS GEL-NYC — Black','asics-gel-nyc-black','ASICS','GEL-NYC','Black',449.99,419.99,'assets/images/products/stock/asics-gel-nyc-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Alexander McQueen Oversized Sneaker — Black','alexander-mcqueen-oversized-sneaker-black','Alexander McQueen','Oversized Sneaker','Black',399.99,370.0,'assets/images/products/stock/alexander-mcqueen-oversized-sneaker-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Alexander McQueen Oversized Sneaker — Black White','alexander-mcqueen-oversized-sneaker-black-white','Alexander McQueen','Oversized Sneaker','Black White',399.99,370.0,'assets/images/products/stock/alexander-mcqueen-oversized-sneaker-black-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Alexander McQueen Oversized Sneaker — Black Sole White','alexander-mcqueen-oversized-sneaker-black-sole-white','Alexander McQueen','Oversized Sneaker','Black Sole White',399.99,370.0,'assets/images/products/stock/alexander-mcqueen-oversized-sneaker-black-sole-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Alexander McQueen Oversized Sneaker — White Black','alexander-mcqueen-oversized-sneaker-white-black','Alexander McQueen','Oversized Sneaker','White Black',399.99,370.0,'assets/images/products/stock/alexander-mcqueen-oversized-sneaker-white-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Alexander McQueen Oversized Sneaker — White','alexander-mcqueen-oversized-sneaker-white','Alexander McQueen','Oversized Sneaker','White',399.99,370.0,'assets/images/products/stock/alexander-mcqueen-oversized-sneaker-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,true,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Mind 001 — Sail','nike-mind-001-sail','Nike','Mind 001','Sail',279.99,240.0,'assets/images/products/stock/nike-mind-001-sail.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Mind 001 — Black Chrome','nike-mind-001-black-chrome','Nike','Mind 001','Black Chrome',279.99,240.0,'assets/images/products/stock/nike-mind-001-black-chrome.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Mind 001 — White','nike-mind-001-white','Nike','Mind 001','White',279.99,240.0,'assets/images/products/stock/nike-mind-001-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Mind 001 — University Red','nike-mind-001-university-red','Nike','Mind 001','University Red',279.99,240.0,'assets/images/products/stock/nike-mind-001-university-red.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Mind 001 — Blackened Blue','nike-mind-001-blackened-blue','Nike','Mind 001','Blackened Blue',279.99,240.0,'assets/images/products/stock/nike-mind-001-blackened-blue.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Puma Mercedes-AMG Motorsport — White Blue','puma-mercedes-amg-motorsport-white-blue','Puma','Mercedes-AMG Motorsport','White Blue',389.99,360.0,'assets/images/products/stock/puma-mercedes-amg-motorsport-white-blue.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Puma BMW M Motorsport — White','puma-bmw-m-motorsport-white','Puma','BMW M Motorsport','White',389.99,360.0,'assets/images/products/stock/puma-bmw-m-motorsport-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Puma BMW M Motorsport — Black Red Blue','puma-bmw-m-motorsport-black-red-blue','Puma','BMW M Motorsport','Black Red Blue',389.99,360.0,'assets/images/products/stock/puma-bmw-m-motorsport-black-red-blue.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Puma BMW M Motorsport — Black','puma-bmw-m-motorsport-black','Puma','BMW M Motorsport','Black',389.99,360.0,'assets/images/products/stock/puma-bmw-m-motorsport-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Puma Mercedes-AMG Motorsport — Black Aqua','puma-mercedes-amg-motorsport-black-aqua','Puma','Mercedes-AMG Motorsport','Black Aqua',389.99,360.0,'assets/images/products/stock/puma-mercedes-amg-motorsport-black-aqua.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Tommy Hilfiger Corporate Sneaker — Grey','tommy-hilfiger-corporate-sneaker-grey','Tommy Hilfiger','Corporate Sneaker','Grey',389.99,360.0,'assets/images/products/stock/tommy-hilfiger-corporate-sneaker-grey.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Tommy Hilfiger Signature Sneaker — White','tommy-hilfiger-signature-sneaker-white','Tommy Hilfiger','Signature Sneaker','White',389.99,360.0,'assets/images/products/stock/tommy-hilfiger-signature-sneaker-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Tommy Hilfiger Signature Sneaker — Black','tommy-hilfiger-signature-sneaker-black','Tommy Hilfiger','Signature Sneaker','Black',389.99,360.0,'assets/images/products/stock/tommy-hilfiger-signature-sneaker-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Tommy Hilfiger Corporate Sneaker — White','tommy-hilfiger-corporate-sneaker-white','Tommy Hilfiger','Corporate Sneaker','White',389.99,360.0,'assets/images/products/stock/tommy-hilfiger-corporate-sneaker-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Dracula','nike-air-max-plus-tn-dracula','Nike','Air Max Plus TN','Dracula',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-dracula.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Triple White','nike-air-max-plus-tn-triple-white','Nike','Air Max Plus TN','Triple White',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-triple-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Black White','nike-air-max-plus-tn-black-white','Nike','Air Max Plus TN','Black White',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-black-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — FC Barcelona','nike-air-max-plus-tn-fc-barcelona','Nike','Air Max Plus TN','FC Barcelona',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-fc-barcelona.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Deadpool','nike-air-max-plus-tn-deadpool','Nike','Air Max Plus TN','Deadpool',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-deadpool.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Baltic Blue','nike-air-max-plus-tn-baltic-blue','Nike','Air Max Plus TN','Baltic Blue',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-baltic-blue.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Triple Black','nike-air-max-plus-tn-triple-black','Nike','Air Max Plus TN','Triple Black',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-triple-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Black Blue','nike-air-max-plus-tn-black-blue','Nike','Air Max Plus TN','Black Blue',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-black-blue.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN — Celestine Blue','nike-air-max-plus-tn-celestine-blue','Nike','Air Max Plus TN','Celestine Blue',389.99,359.99,'assets/images/products/stock/nike-air-max-plus-tn-celestine-blue.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 13 — Preto Dourado','mizuno-wave-prophecy-13-preto-dourado','Mizuno','Wave Prophecy 13','Preto Dourado',499.99,480.0,'assets/images/products/stock/mizuno-wave-prophecy-13-preto-dourado.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 13 — Grafite Vermelho','mizuno-wave-prophecy-13-grafite-vermelho','Mizuno','Wave Prophecy 13','Grafite Vermelho',499.99,480.0,'assets/images/products/stock/mizuno-wave-prophecy-13-grafite-vermelho.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 13 — Cinza Vermelho','mizuno-wave-prophecy-13-cinza-vermelho','Mizuno','Wave Prophecy 13','Cinza Vermelho',499.99,480.0,'assets/images/products/stock/mizuno-wave-prophecy-13-cinza-vermelho.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 13 — Preto Azul','mizuno-wave-prophecy-13-preto-azul','Mizuno','Wave Prophecy 13','Preto Azul',499.99,480.0,'assets/images/products/stock/mizuno-wave-prophecy-13-preto-azul.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 13 — Preto Laranja','mizuno-wave-prophecy-13-preto-laranja','Mizuno','Wave Prophecy 13','Preto Laranja',499.99,480.0,'assets/images/products/stock/mizuno-wave-prophecy-13-preto-laranja.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 13 — Preto','mizuno-wave-prophecy-13-preto','Mizuno','Wave Prophecy 13','Preto',499.99,480.0,'assets/images/products/stock/mizuno-wave-prophecy-13-preto.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 15 — Preto Prata','mizuno-wave-prophecy-15-preto-prata','Mizuno','Wave Prophecy 15','Preto Prata',559.99,520.0,'assets/images/products/stock/mizuno-wave-prophecy-15-preto-prata.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 15 — Branco Dourado','mizuno-wave-prophecy-15-branco-dourado','Mizuno','Wave Prophecy 15','Branco Dourado',559.99,520.0,'assets/images/products/stock/mizuno-wave-prophecy-15-branco-dourado.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 15 — Preto Dourado','mizuno-wave-prophecy-15-preto-dourado','Mizuno','Wave Prophecy 15','Preto Dourado',559.99,520.0,'assets/images/products/stock/mizuno-wave-prophecy-15-preto-dourado.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Shox R4 — Black Silver','nike-shox-r4-black-silver','Nike','Shox R4','Black Silver',279.99,240.0,'assets/images/products/stock/nike-shox-tl-black-silver.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Shox R4 — Black Silver Red','nike-shox-r4-black-silver-red','Nike','Shox R4','Black Silver Red',279.99,240.0,'assets/images/products/stock/nike-shox-tl-black-silver-red.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Shox R4 — Black','nike-shox-r4-black','Nike','Shox R4','Black',279.99,240.0,'assets/images/products/stock/nike-shox-tl-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Shox R4 — Preto Vermelho','nike-shox-r4-preto-vermelho','Nike','Shox R4','Preto Vermelho',279.99,240.0,'assets/images/products/stock/nike-shox-tl-preto-vermelho.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 1 — Preto','mizuno-wave-prophecy-1-preto','Mizuno','Wave Prophecy 1','Preto',489.99,470.0,'assets/images/products/stock/mizuno-wave-prophecy-1-preto.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 1 — Branco','mizuno-wave-prophecy-1-branco','Mizuno','Wave Prophecy 1','Branco',489.99,470.0,'assets/images/products/stock/mizuno-wave-prophecy-1-branco.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN7 — White Black','nike-air-max-plus-tn7-white-black','Nike','Air Max Plus TN7','White Black',399.99,369.99,'assets/images/products/stock/nike-air-max-plus-tn7-white-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN7 — Black','nike-air-max-plus-tn7-black','Nike','Air Max Plus TN7','Black',399.99,369.99,'assets/images/products/stock/nike-air-max-plus-tn7-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN7 — University Red','nike-air-max-plus-tn7-university-red','Nike','Air Max Plus TN7','University Red',399.99,369.99,'assets/images/products/stock/nike-air-max-plus-tn7-university-red.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN7 — Vintage Green','nike-air-max-plus-tn7-vintage-green','Nike','Air Max Plus TN7','Vintage Green',399.99,369.99,'assets/images/products/stock/nike-air-max-plus-tn7-vintage-green.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max Plus TN7 — Bumblebee','nike-air-max-plus-tn7-bumblebee','Nike','Air Max Plus TN7','Bumblebee',399.99,369.99,'assets/images/products/stock/nike-air-max-plus-tn7-bumblebee.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Corteiz Gutta Green','nike-air-max-95-corteiz-gutta-green','Nike','Air Max 95','Corteiz Gutta Green',429.99,389.99,'assets/images/products/stock/nike-air-max-95-corteiz-gutta-green.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — White','nike-air-max-95-white','Nike','Air Max 95','White',429.99,389.99,'assets/images/products/stock/nike-air-max-95-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Corteiz Aegean Storm','nike-air-max-95-corteiz-aegean-storm','Nike','Air Max 95','Corteiz Aegean Storm',429.99,389.99,'assets/images/products/stock/nike-air-max-95-corteiz-aegean-storm.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Corteiz Honey Blacks','nike-air-max-95-corteiz-honey-blacks','Nike','Air Max 95','Corteiz Honey Blacks',429.99,389.99,'assets/images/products/stock/nike-air-max-95-corteiz-honey-blacks.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Black Neon','nike-air-max-95-black-neon','Nike','Air Max 95','Black Neon',429.99,389.99,'assets/images/products/stock/nike-air-max-95-black-neon.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Bright Mandarin','nike-air-max-95-bright-mandarin','Nike','Air Max 95','Bright Mandarin',429.99,389.99,'assets/images/products/stock/nike-air-max-95-bright-mandarin.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Triple Black','nike-air-max-95-triple-black','Nike','Air Max 95','Triple Black',429.99,389.99,'assets/images/products/stock/nike-air-max-95-triple-black.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Solar Red','nike-air-max-95-solar-red','Nike','Air Max 95','Solar Red',429.99,389.99,'assets/images/products/stock/nike-air-max-95-solar-red.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Neon','nike-air-max-95-neon','Nike','Air Max 95','Neon',429.99,389.99,'assets/images/products/stock/nike-air-max-95-neon.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Stadium Green','nike-air-max-95-stadium-green','Nike','Air Max 95','Stadium Green',429.99,389.99,'assets/images/products/stock/nike-air-max-95-stadium-green.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Corteiz Pink Beam','nike-air-max-95-corteiz-pink-beam','Nike','Air Max 95','Corteiz Pink Beam',429.99,389.99,'assets/images/products/stock/nike-air-max-95-corteiz-pink-beam.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Nike Air Max 95 — Black and White','nike-air-max-95-black-and-white','Nike','Air Max 95','Black and White',429.99,389.99,'assets/images/products/stock/nike-air-max-95-black-and-white.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 14 — Roxo','mizuno-wave-prophecy-14-roxo','Mizuno','Wave Prophecy 14','Roxo',529.99,490.0,'assets/images/products/stock/mizuno-wave-prophecy-14-roxo.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 14 — Preto Cinza Vermelho','mizuno-wave-prophecy-14-preto-cinza-vermelho','Mizuno','Wave Prophecy 14','Preto Cinza Vermelho',529.99,490.0,'assets/images/products/stock/mizuno-wave-prophecy-14-preto-cinza-vermelho.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 14 — Cinza Verde Água','mizuno-wave-prophecy-14-cinza-verde-agua','Mizuno','Wave Prophecy 14','Cinza Verde Água',529.99,490.0,'assets/images/products/stock/mizuno-wave-prophecy-14-cinza-verde-agua.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 14 — Branco Rosa','mizuno-wave-prophecy-14-branco-rosa','Mizuno','Wave Prophecy 14','Branco Rosa',529.99,490.0,'assets/images/products/stock/mizuno-wave-prophecy-14-branco-rosa.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 14 — Branco','mizuno-wave-prophecy-14-branco','Mizuno','Wave Prophecy 14','Branco',529.99,490.0,'assets/images/products/stock/mizuno-wave-prophecy-14-branco.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 14 — Preto Dourado','mizuno-wave-prophecy-14-preto-dourado','Mizuno','Wave Prophecy 14','Preto Dourado',529.99,490.0,'assets/images/products/stock/mizuno-wave-prophecy-14-preto-dourado.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
insert into public.products(name,slug,brand,model,color,old_price,price,image,sizes,stock,active,featured,best_seller,promotion)
values('Mizuno Wave Prophecy 14 — Preto Cinza','mizuno-wave-prophecy-14-preto-cinza','Mizuno','Wave Prophecy 14','Preto Cinza',529.99,490.0,'assets/images/products/stock/mizuno-wave-prophecy-14-preto-cinza.jpg',ARRAY[38,39,40,41,42,43,44],1997,true,false,false,false)
on conflict(slug) do update set name=excluded.name,brand=excluded.brand,model=excluded.model,color=excluded.color,old_price=excluded.old_price,price=excluded.price,image=excluded.image,sizes=excluded.sizes,stock=excluded.stock,active=excluded.active,featured=excluded.featured;
